[tool.poetry]
name = "gpt-hary"
version = "0.1.0"
description = ""
authors = ["haru <88703915+lips85@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
